/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ican_cocos2dx_jni_LFCocos2dxHelper */

#ifndef _Included_com_ican_cocos2dx_jni_LFCocos2dxHelper
#define _Included_com_ican_cocos2dx_jni_LFCocos2dxHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ican_cocos2dx_jni_LFCocos2dxHelper
 * Method:    gameActivityOnPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ican_cocos2dx_jni_LFCocos2dxHelper_gameActivityOnPause
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
